name: sing-box
version: "1.14.2-1"
slug: sing-box
description: sing-box proxy service for Home Assistant
url: https://github.com/onikyannn/home-assistant-sign-box/tree/master/sing-box

arch:
  - aarch64
  - amd64

startup: services
boot: auto
host_network: true
init: false
watchdog: http://[HOST]:18787/health

panel_icon: mdi:shield-outline

devices:
  - /dev/net/tun

privileged:
  - NET_ADMIN
  - NET_RAW

options:
  config_url: null

schema:
  config_url: url
  config_username: str?
  config_password: password?
